ALTER TABLE SelectCourse  
	ALTER COLUMN sno CHAR(12) NOT NULL;
ALTER TABLE SelectCourse  
	ALTER COLUMN schoolYear TINYINT NOT NULL;
ALTER TABLE SelectCourse  
	ALTER COLUMN semester TINYINT NOT NULL;  
ALTER TABLE SelectCourse  
	ALTER COLUMN courseNo CHAR(6) NOT NULL;